### ISSUE TITLE
[EPIC] General Improvements

### ISSUE THREAD

**Issue by emerkle826** [k8ssandra/management-api-for-apache-cassandra#429]
Certain aspects of this project have made recent changes and improvements fairly challenging to realize. The goal of this ticket is to capture a few of the more painful items to try to make developing and testing a little easier and more broadly maintainable.

```[tasklist]
- [ ] Use Java NIO as fallback for Netty when epoll is not available
- [ ] Replace internal serialization framework in Agent
- [ ] Improve version management
- [ ] Refactor OpenAPI client generation
```
